apps/enquiries/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


urlpatterns = [
    path('delete/<slug:slug>/', csrf_exempt(views.enquiry_delete_view), name='delete'),
    path('edit/<slug:slug>/', views.EnquiryUpdateView.as_view(), name='update'),
    path('get_cities/', csrf_exempt(views.GetStateCities.as_view()), name="get_cities"),
    path('create/', csrf_exempt(views.EnquiryCreateView.as_view()), name='create'),
    path('my_enquiry_list/', views.MyEnquiryList.as_view(), name='my_enquiry_list'),
    path('agent_enquiry_list/', views.AgentEnquiryList.as_view(), name='agent_enquiry_list'),
    path('my_enquiries/', views.MyEnquiries.as_view(), name='my_enquiries'),
    path('<slug:slug>/payment/', views.EnquiryPaymentView.as_view(), name='payment'),
    path('<slug:slug>/', views.EnquiryDetailView.as_view(), name='detail'),
    path('', views.EnquiryListView.as_view(), name='list'),
]

propertyDealsIn9ja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from propertyDealsIn9ja.settings import DEBUG
from propertyDealsIn9ja.views import HomeView, filter_property

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', csrf_exempt(HomeView.as_view()), name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/', include(('apps.accounts.urls', 'apps.accounts'), namespace='accounts')),
    path('api/accounts/', include(('apps.accounts.api.urls', 'apps.accounts'), namespace='api_accounts')),
    path('social-auth', include('social_django.urls', namespace='social')),
    path('profiles/', include(('apps.profiles.urls', 'apps.profiles'), namespace='profiles')),
    path('api/profiles/', include(('apps.profiles.api.urls', 'apps.profiles'), namespace='profiles_api')),
    path('contacts/', include(('apps.contacts.urls', 'apps.contacts'), namespace="contacts")),
    path('agents/', include(('apps.agents.urls', 'apps.agents'), namespace="agents")),
    path('properties/', include(('apps.properties.urls', 'apps.properties'), namespace="properties")),
    path('enquiries/', include(('apps.enquiries.urls', 'apps.enquiries'), namespace="enquiries")),
    path('wallets/', include(('apps.wallets.urls', 'apps.wallets'), namespace="wallets")),
    path('chats/', include(('apps.chats.urls', 'apps.chats'), namespace='chats')),
    path('inbox/', include(('apps.inboxes.urls', 'apps.inboxes'), namespace='inboxes')),
    path('notifications/', include(('apps.notifications.urls', 'apps.notifications'), namespace='notifications')),
    path('filter_property/', csrf_exempt(filter_property), name='filter_property'),

]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='404.html'))]

admin.site.site_header = "PropertyDealsIn9ja Admin"
admin.site.site_title = "PropertyDealsIn9ja Admin Portal"
admin.site.site_title = "Welcome to the PropertyDealsIn9ja administration"

apps/enquiries/models.py
from autoslug import AutoSlugField
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from apps.common.models import TimeStampedUUIDModel
from apps.notifications.models import Notification


class EnquiryQuerySet(models.query.QuerySet):
    def is_an_open_enquiry(self):
        return self.filter(is_open=True)


class EnquiryManager(models.Manager):
    def get_queryset(self):
        return EnquiryQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().is_an_open_enquiry()


class Enquiry(TimeStampedUUIDModel):
    class Types(models.TextChoices):
        APARTMENT = 'Apartment'
        LAND = 'Land'
        BQ = 'BQ'
        TERRACE = 'Terrace'
        SEMI_DETACHED = 'Semi Detached'
        FULLY_DETACHED = 'Fully Detached'
        OFFICE = 'Office'
        WAREHOUSE = 'Warehouse'
        COMMERCIAL = 'Commercial'
        OTHER = 'Other'

    class Status(models.TextChoices):
        FOR_RENT = 'For Rent'
        FOR_SALE = 'For Sale'
        AUCTION = 'Auction'
        SOLD = 'Sold'
        RENTED = 'Rented'

    class EnquiryStatus(models.TextChoices):
        ASSIGNED = 'Assigned'
        OPEN = 'Open'

    from_user = models.ForeignKey("accounts.User", related_name="user_enquiries", on_delete=models.DO_NOTHING, blank=True, null=True)
    to_agent = models.ForeignKey("agents.Agent", related_name="agent_enquiries", on_delete=models.DO_NOTHING, blank=True, null=True)
    enquiry_state = models.CharField(help_text="State", max_length=144, blank=True, null=True)
    enquiry_city = models.CharField(help_text="City/LGA", max_length=144, blank=True, null=True)
    enquiry_Address = models.CharField(help_text="Local Area/Bustops/Park", max_length=144, blank=True, null=True)
    slug = AutoSlugField(populate_from='from_user', unique_with='enquiry_date', unique=True, always_update=True)
    enquiry_property_type = models.CharField(choices=Types.choices, max_length=144, blank=True, null=True, default="Type")
    enquiry_property_status = models.CharField(choices=Status.choices, max_length=144, blank=True, null=True, default="Status")
    enquiry_description = models.TextField(help_text="Tell us more about what you need.", blank=True, null=True)
    enquiry_budget_min = models.DecimalField(help_text="Your Minimum Budget", max_digits=10, decimal_places=2)
    enquiry_budget_max = models.DecimalField(help_text="Your Maximum Budget", max_digits=10, decimal_places=2)
    enquiry_price = models.DecimalField(help_text="0.00", max_digits=10, decimal_places=2, default=0.00, blank=True, null=True)
    enquiry_on_promo = models.BooleanField(default=True)
    inspection_date = models.DateTimeField()
    # is_open = models.BooleanField(default=True)
    status = models.CharField(max_length=100, choices=EnquiryStatus.choices, blank=True, null=True, default="Open")
    enquiry_date = models.DateTimeField(default=timezone.now)
    # objects = EnquiryManager()

    class Meta:
        verbose_name_plural = "Enquiries"
        ordering = ("-enquiry_date",)

    def __str__(self):
        return f"{self.enquiry_property_type}-{self.enquiry_property_status}"

    # def get_absolute_url(self):
    #     return redirect('enquiries:my_enquiry_list')

    @property
    def name(self):
        return f"{self.enquiry_property_type} Enquiry for {self.enquiry_property_status}"

    @property
    def enquiry_address(self):
        return f"{self.enquiry_state}, {self.enquiry_city}"


@receiver(post_save, sender=Enquiry)
def user_add_enquiry_notification(sender, instance, *args, **kwargs):
    enquiry = instance
    sender = enquiry.from_user
    message = f"Your enquiry was added successfully an Agent will get back to you shortly."
    notify = Notification(
        from_user=sender,
        to_user=sender,
        notification_type=4,
        message=message,
    )
    notify.save()

apps/enquiries/forms.py
from django.forms import ModelForm
from apps.enquiries.models import Enquiry


class EnquiryForm(ModelForm):
    class Meta:
        model = Enquiry
        fields = [
            "enquiry_state",
            "enquiry_city",
            "enquiry_property_type",
            "enquiry_property_status",
            "enquiry_description",
            "enquiry_budget_min",
            "enquiry_budget_max",
            "inspection_date",
        ]

apps/enquiries/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from apps.enquiries.forms import EnquiryForm
from apps.enquiries.models import Enquiry
from apps.wallets.models import Wallet, WalletTransaction
from propertyDealsIn9ja.utils import get_states_only, get_cities_only


class EnquiryListView(ListView):
    model = Enquiry
    paginate_by = 6
    template_name = "enquiries/list.html"
    context_object_name = "enquiries"
    queryset = Enquiry.objects.filter(status="Open")


class EnquiryDetailView(DetailView):
    model = Enquiry
    template_name = "enquiries/detail.html"
    context_object_name = "enquiry"


class EnquiryPaymentView(View):

    def get(self, request, slug):
        enquiry = get_object_or_404(Enquiry, slug=slug)
        wallet = self.request.user.wallet
        if enquiry.enquiry_on_promo:
            # Update the enquiry
            enquiry.to_agent = self.request.user.agent
            enquiry.status = "Assigned"
            enquiry.save(update_fields=['to_agent', 'status'])
            messages.success(request, "Enquiry added to your list")
            return redirect("enquiries:detail", enquiry.slug)
        elif wallet.balance >= enquiry.enquiry_price:
            wallet.balance = F('balance') - enquiry.enquiry_price
            wallet.save()
            # Update the enquiry
            enquiry.to_agent = self.request.user.agent
            enquiry.status = "Assigned"
            enquiry.save(update_fields=['to_agent', 'status'])
            wallet_transaction = WalletTransaction.objects.create(
                wallet=wallet,
                transaction_id=enquiry.name[:6],
                currency=wallet.currency,
                amount=enquiry.enquiry_price,
                payment_status="Success",
            )
            wallet.wallet_transactions.add(wallet_transaction)
            messages.success(request, "Enquiry bought and added to your list")
            return redirect("enquiries:detail", enquiry.slug)
        messages.error(request, "Low balance please fund your wallet")
        return redirect("wallets:fund_wallet", self.request.user.wallet.uid)


class EnquiryCreateView(LoginRequiredMixin, CreateView):
    template_name = "enquiries/create_form.html"
    form_class = EnquiryForm

    def get_context_data(self, **kwargs):
        context = super(EnquiryCreateView, self).get_context_data()
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        context["states"] = get_states_only(file_path)
        return context

    def form_valid(self, form):
        user = self.request.user
        # create address
        state = self.request.POST.get("state")
        city = self.request.POST.get("city")
        enquiry_property_type = form.cleaned_data['enquiry_property_type']
        enquiry_property_status = form.cleaned_data['enquiry_property_status']
        enquiry_description = form.cleaned_data['enquiry_description']
        enquiry_budget_min = form.cleaned_data['enquiry_budget_min']
        enquiry_budget_max = form.cleaned_data['enquiry_budget_max']
        inspection_date = form.cleaned_data['inspection_date']
        print("About to create Enquiry.")
        Enquiry.objects.create(
            from_user=user,
            enquiry_state=state,
            enquiry_city=city,
            enquiry_property_type=enquiry_property_type,
            enquiry_property_status=enquiry_property_status,
            enquiry_description=enquiry_description,
            enquiry_budget_min=enquiry_budget_min,
            enquiry_budget_max=enquiry_budget_max,
            inspection_date=inspection_date,
        ).save()
        print("Enquiry Added.")
        messages.success(self.request, "Enquiry added successfully.")
        if self.request.POST.get('next') != '':
            return redirect(self.request.POST.get('next'))
        return redirect('home')
        # return super(EnquiryCreateView, self).form_valid()


class EnquiryUpdateView(LoginRequiredMixin, UpdateView):
    model = Enquiry
    template_name = "enquiries/update_form.html"
    context_object_name = "enquiry"
    fields = [
        "enquiry_state",
        "enquiry_city",
        "enquiry_property_type",
        "enquiry_property_status",
        "enquiry_description",
        "enquiry_budget_min",
        "enquiry_budget_max",
        "inspection_date",
    ]

    def get_context_data(self, **kwargs):
        context = super(EnquiryUpdateView, self).get_context_data()
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        context["states"] = get_states_only(file_path)
        return context


class EnquiryDeleteView(LoginRequiredMixin, View):

    def get(self, request, slug):
        prop_obj = Enquiry.objects.filter(slug=slug)
        prop_obj.delete()
        return HttpResponse("<script type=text/javascript>toastr.success('Enquiry deleted successfully')</script>")


def enquiry_delete_view(request, slug):
    prop_obj = Enquiry.objects.filter(slug=slug)
    prop_obj.delete()
    return HttpResponse("<script type=text/javascript>toastr.success('Enquiry deleted successfully')</script>")


class MyEnquiries(View):
    template_name = "enquiries/my_enquiries.html"

    def get(self, request):
        enquiries = Enquiry.objects.filter(from_user=self.request.user)
        context = {
            "enquiries": enquiries,
        }
        return render(request, self.template_name, context)


class MyEnquiryList(View):
    template_name = "enquiries/my_list_htmx.html"

    def get(self, request):
        enquiries = Enquiry.objects.filter(from_user=self.request.user)
        context = {
            "enquiries": enquiries,
        }
        return render(request, self.template_name, context)


class AgentEnquiryList(View):
    template_name = "enquiries/agent_enquiry_list.html"

    def get(self, request):
        user = self.request.user
        enquiries = Enquiry.objects.filter(to_agent=user.agent)
        context = {
            "enquiries": enquiries,
        }
        return render(request, self.template_name, context)


class GetStateCities(View):
    template_name = "enquiries/create_form.html"

    def post(self, request):
        state = request.POST['state']
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        cities = get_cities_only(file_path, state)
        data = {
            "cities": cities,
            "success": "request was successful cities populated..."
        }
        return JsonResponse(data=data, safe=False)

apps/enquiries/templates/enquiries/agent_enquiry_list.html
{% extends 'user_layout.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block content %}
    <div class="col-lg-4 col-xl-4 mb10">
        <div class="breadcrumb_content style2 mb30-991">
            <h2 class="breadcrumb_title">My Assigned Enquiries</h2>
            <p>Below are your uploaded enquiries and their status</p>
        </div>
    </div>
<!--    <div class="col-lg-8 col-xl-8">-->
<!--        <div class="candidate_revew_select style2 text-right mb30-991">-->
<!--           <button type="button" hx-get="{% url 'enquiries:create' %}" hx-target="#enquiry_dialog" data-toggle="modal" data-target=".enquiry_modal" class="btn dbxshad btn-lg btn-dark circle"><i class="fa fa-plus"></i></button>-->
<!--        </div>-->
<!--        <div class="sign_up_modal modal fade enquiry_modal" tabindex="-1" role="dialog" aria-hidden="true">-->
<!--            <div id="enquiry_dialog" class="modal-dialog modal-lg" role="document">-->
<!--                &lt;!&ndash; Injects enquiry Form here &ndash;&gt;-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <div class="col-lg-12">
        <div class="my_dashboard_review mb40">
            <div class="col-lg-12">
                <div class="savesearched_table">
                    <div class="table-responsive mt0">
                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Enquiry</th>
                                    <th scope="col">Prop Type</th>
                                    <th scope="col">Prop Status</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Assigned Agent</th>
                                    <th scope="col">Created</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for e in enquiries %}
                                    <tr>
                                        <th class="title">{{e.enquiry_address}}</th>
                                        <td>{{e.enquiry_property_type}}</td>
                                        <td>{{e.enquiry_property_status}}</td>
                                        <td>
                                            {% if e.status == "Open" %}
                                                <span class="badge badge-pill badge-warning">
                                                    {{e.status}}
                                                </span>
                                            {% else %}
                                                <span class="badge badge-pill badge-success">
                                                    {{e.status}}
                                                </span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if e.to_agent %}
                                                <span class="badge badge-pill badge-success">
                                                    Assigned to {{e.to_agent}}
                                                </span>
                                            {% else %}
                                                <span class="badge badge-pill badge-warning">
                                                    Yet to be assigned
                                                </span>
                                            {% endif %}
                                        </td>
                                        <td class="para">{{e.enquiry_date|timesince}}</td>
                                        <td>
                                            <ul class="view_edit_delete_list mb0">
                                                <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View"><a href="{% url 'enquiries:detail' e.slug %}"><span class="flaticon-view"></span></a></li>
                                                <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                    <a hx-delete="{% url 'enquiries:delete' e.slug %}" hx-confirm="Do you wish to delete?" onClick="setTimeout(function(){ window.location.reload(); }, 3000);">
                                                        <span class="flaticon-garbage"></span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                {% empty %}
<!--                                    <tr>You have not yet made an enquiry.</tr>-->
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

apps/enquiries/templates/enquiries/list.html
{% extends 'layout.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block title %}Enquiries{% endblock title %}

{% block content %}
    <!-- Inner Page Breadcrumb -->
    <section class="inner_page_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-xl-6">
                    <div class="breadcrumb_content">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Enquiries</li>
                        </ol>
                        <h4 class="breadcrumb_title">Enquiries</h4>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Property Cities -->
    <section id="property-city" class="property-city pb30">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="main-title text-center">
                        <h2>List of Enquiries From our Clients</h2>
                        <p>Our clients' preferences for your city/area of service are given below. </p>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for e in enquiries %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
                        <div class="property_city_home6">
                            <div class="thumb">
                                {% if e.enquiry_property_type == "Apartment" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/apartment.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Land" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/land-sales.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "BQ" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/neighbour.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Terrace" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/building-with-rooftop-terrace.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Semi Detached" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/bungalow.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Fully Detached" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/bungalow.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Office" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/link-company-parent.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Warehouse" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/warehouse-1.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Commercial" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/sell-property.png" alt="{{e.enquiry_property_type}}">
                                {% elif e.enquiry_property_type == "Other" %}
                                    <img class="w100" style="height: 200px" src="https://img.icons8.com/material-rounded/96/FA5252/house-with-a-garden.png" alt="{{e.enquiry_property_type}}">
                                {% endif %}
                            </div>
                            <div class="details">
                                <h4>A Client from {{e.enquiry_address}}</h4>
                                <p>Needs {{e.enquiry_property_type}} property</p>
                                <a href="{% url 'enquiries:payment' e.slug %}">
                                    <small><div class="fp_pdate float-right text-thm">Click to purchase & attend to this customer <i class="fa fa-angle-right"></i></div></small>
                                </a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="col-md-12 col-lg-12">
                        <div class="feat_property list style2 agent">
                            <div class="details">
                                <div class="tc_content">
                                    <h4>Enquiry Currently Unavailable</h4>
                                    <br>
                                    <p>We do not currently have any available inquiries from our clients that cover your city/area; please check again later for availability. </p>
                                    <br>
                                    {% if request.user.is_authenticated and request.user.is_agent %}
                                        <a href="{% url 'enquiries:agent_enquiry_list' %}" class="btn dbxshad btn-sm btn-thm2 circle"><i class="fa fa-plus"></i> My Assigned Enquiries</a>
                                    {% else %}
                                        <a href="{% url 'enquiries:create' %}" class="btn dbxshad btn-sm btn-thm2 circle"><i class="fa fa-plus"></i> Enquire</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock content %}

apps/enquiries/templates/enquiries/my_enquiries.html
{% extends 'user_layout.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="col-lg-4 col-xl-4 mb10">
        <div class="breadcrumb_content style2 mb30-991">
            <h2 class="breadcrumb_title">My Enquiries</h2>
            <p>Below are your uploaded enquiries and their status</p>
        </div>
    </div>
<!--    <div class="col-lg-8 col-xl-8">-->
<!--        <div class="candidate_revew_select style2 text-right mb30-991">-->
<!--           <button type="button" hx-get="{% url 'enquiries:create' %}" hx-target="#enquiry_dialog" data-toggle="modal" data-target=".enquiry_modal" class="btn dbxshad btn-lg btn-dark circle"><i class="fa fa-plus"></i></button>-->
<!--        </div>-->
<!--        <div class="sign_up_modal modal fade enquiry_modal" tabindex="-1" role="dialog" aria-hidden="true">-->
<!--            <div id="enquiry_dialog" class="modal-dialog modal-lg" role="document">-->
<!--                &lt;!&ndash; Injects enquiry Form here &ndash;&gt;-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <div class="col-lg-12">
        <div class="my_dashboard_review mb40">
            <div class="col-lg-12">
                <div class="savesearched_table">
                    <div class="table-responsive mt0">
                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Enquiry</th>
                                    <th scope="col">Prop Type</th>
                                    <th scope="col">Prop Status</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Assigned Agent</th>
                                    <th scope="col">Created</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody hx-get="{% url 'enquiries:my_enquiry_list' %}" hx-trigger="load">
                            <!-- Injects enquiry lists here -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

apps/enquiries/templates/enquiries/my_list_htmx.html
{% load humanize %}

{% for e in enquiries %}
    <tr>
        <th class="title">{{e.enquiry_address}}</th>
        <td>{{e.enquiry_property_type}}</td>
        <td>{{e.enquiry_property_status}}</td>
        <td>
            {% if e.status == "Open" %}
                <span class="badge badge-pill badge-warning">
                    {{e.status}}
                </span>
            {% else %}
                <span class="badge badge-pill badge-success">
                    {{e.status}}
                </span>
            {% endif %}
        </td>
        <td>
            {% if e.to_agent %}
                <span class="badge badge-pill badge-success">
                    Assigned to {{e.to_agent}}
                </span>
            {% else %}
                <span class="badge badge-pill badge-warning">
                    Yet to be assigned
                </span>
            {% endif %}
        </td>
        <td class="para">{{e.enquiry_date|timesince}}</td>
        <td>
            <ul class="view_edit_delete_list mb0">
                <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View"><a href="{% url 'enquiries:detail' e.slug %}"><span class="flaticon-view"></span></a></li>
                {% if e.status == "Open" %}
                    <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="Delete">
                        <a hx-delete="{% url 'enquiries:delete' e.slug %}" hx-confirm="Do you wish to delete?" onClick="setTimeout(function(){ window.location.reload(); }, 3000);">
                            <span class="flaticon-garbage"></span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </td>
    </tr>
{% empty %}
    <tr>You have not yet made an enquiry.</tr>
{% endfor %}