apps/enquiries/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


urlpatterns = [
    path('delete/<slug:slug>/', csrf_exempt(views.enquiry_delete_view), name='delete'),
    path('edit/<slug:slug>/', views.EnquiryUpdateView.as_view(), name='update'),
    path('get_cities/', csrf_exempt(views.GetStateCities.as_view()), name="get_cities"),
    path('create/', csrf_exempt(views.EnquiryCreateView.as_view()), name='create'),
    path('my_enquiry_list/', views.MyEnquiryList.as_view(), name='my_enquiry_list'),
    path('agent_enquiry_list/', views.AgentEnquiryList.as_view(), name='agent_enquiry_list'),
    path('my_enquiries/', views.MyEnquiries.as_view(), name='my_enquiries'),
    path('<slug:slug>/payment/', views.EnquiryPaymentView.as_view(), name='payment'),
    path('<slug:slug>/', views.EnquiryDetailView.as_view(), name='detail'),
    path('', views.EnquiryListView.as_view(), name='list'),
]

apps/inboxes/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from apps.inboxes import views

urlpatterns = [
    path('', views.InboxMessageView.as_view(), name='inbox_msg'),
    path('<str:username>/', views.DirectMessage.as_view(), name='direct_msg'),
    path('send_direct_msg/', csrf_exempt(views.SendDirectMessage.as_view()), name='send_direct_msg'),
]

apps/properties/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


urlpatterns = [
    # path('upload_file/', csrf_exempt(views.upload_file), name="upload_file"),
    path('comments/<slug:slug>/', csrf_exempt(views.PropertyCommentView.as_view()), name='property_comments'),
    path('dashboard/', views.PropertyDashBoard.as_view(), name='property_dashboard'),
    path('create/', csrf_exempt(views.PropertyCreateView.as_view()), name='create'),
    path('edit/<slug:slug>/', views.PropertyUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', views.property_delete_view, name='delete'),
    path('get_cities/', csrf_exempt(views.GetStateCities.as_view()), name="get_cities"),
    path('favourite_list/', views.MyFavouriteListPropertyView.as_view(), name="get_favourites"),
    path('my_property_list/', views.MyListedProperties.as_view(), name="get_my_property_list"),
    path('add_favorite/', csrf_exempt(views.AddFavoriteProperty.as_view()), name='add_favorite'),
    path('remove_favorite/<slug:slug>/', csrf_exempt(views.RemoveFavoriteProperty.as_view()), name='remove_favorite'),
    path('<slug:slug>/', views.PropertyDetailView.as_view(), name='detail'),
    path('', views.PropertyListView.as_view(), name='list'),
]

apps/wallets/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from apps.wallets.views import FundWalletView, WalletTransactionListView, confirm_fund_view

urlpatterns = [
    # path('validate_bvn/', csrf_exempt(ValidateBVN.as_view()), name='validate_bvn'),
    # path('<slug:id>/fund_success/', csrf_exempt(ConfirmFundView.as_view()), name='fund_success'),
    path('wallet_transactions/', WalletTransactionListView.as_view(), name='wallet_transactions'),
    path('<slug:uid>/', FundWalletView.as_view(), name='fund_wallet'),
    path('<slug:uid>/fund_success/', confirm_fund_view, name='fund_success'),
]

propertyDealsIn9ja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from propertyDealsIn9ja.settings import DEBUG
from propertyDealsIn9ja.views import HomeView, filter_property

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', csrf_exempt(HomeView.as_view()), name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/', include(('apps.accounts.urls', 'apps.accounts'), namespace='accounts')),
    path('api/accounts/', include(('apps.accounts.api.urls', 'apps.accounts'), namespace='api_accounts')),
    path('social-auth', include('social_django.urls', namespace='social')),
    path('profiles/', include(('apps.profiles.urls', 'apps.profiles'), namespace='profiles')),
    path('api/profiles/', include(('apps.profiles.api.urls', 'apps.profiles'), namespace='profiles_api')),
    path('contacts/', include(('apps.contacts.urls', 'apps.contacts'), namespace="contacts")),
    path('agents/', include(('apps.agents.urls', 'apps.agents'), namespace="agents")),
    path('properties/', include(('apps.properties.urls', 'apps.properties'), namespace="properties")),
    path('enquiries/', include(('apps.enquiries.urls', 'apps.enquiries'), namespace="enquiries")),
    path('wallets/', include(('apps.wallets.urls', 'apps.wallets'), namespace="wallets")),
    path('chats/', include(('apps.chats.urls', 'apps.chats'), namespace='chats')),
    path('inbox/', include(('apps.inboxes.urls', 'apps.inboxes'), namespace='inboxes')),
    path('notifications/', include(('apps.notifications.urls', 'apps.notifications'), namespace='notifications')),
    path('filter_property/', csrf_exempt(filter_property), name='filter_property'),

]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='404.html'))]

admin.site.site_header = "PropertyDealsIn9ja Admin"
admin.site.site_title = "PropertyDealsIn9ja Admin Portal"
admin.site.site_title = "Welcome to the PropertyDealsIn9ja administration"

apps/properties/forms.py
from django import forms
from django.forms import ModelForm
from apps.properties.models import Property, PropertyMedia


class PropertyForm(ModelForm):
    class Meta:
        model = Property
        fields = [
            "name",
            "description",
            "property_type",
            "property_status",
            "payment_plan",
            "price",
            "plot_area",
            "no_bed_room",
            "no_bath_room",
            "property_image",
            "exterior_image1",
            "exterior_image2",
            "interior_image1",
            "interior_image2",
            "state",
            "city",
            "local_area",
            "street_address",
            "featured",
        ]


class PropertyMediaForm(ModelForm):
    # property_image = forms.ImageField(
    #     label="Image",
    #     # widget=forms.ClearableFileInput(attrs={"multiple": True}),
    # )

    class Meta:
        model = PropertyMedia
        fields = ("property_image",)

apps/properties/views.py
from msilib.schema import Property
from django.contrib import messages
from django.db.models import F
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from propertyDealsIn9ja.utils import get_states_only, get_cities_only
from .forms import PropertyForm, PropertyMediaForm
from .models import Property, Comment, PropertyMedia
from django.contrib.auth.mixins import LoginRequiredMixin
from .filters import PropertyFilter
from ..agents.models import Agent
from ..notifications.models import Notification
from ..wallets.models import WalletTransaction


class PropertyListView(View):
    paginate_by = 6
    template_name = "properties/list.html"
    
    def get(self, request, *args, **kwargs):
        properties = Property.objects.all()
        # Calling Django Filter...
        property_filter = PropertyFilter(request.GET, queryset=properties)
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        states = get_states_only(file_path)
        # for p in properties:
        #     print(p.property_images.all())
        context = {
            'properties': property_filter.qs,
            'states': states,
            'form': property_filter.form,
        }
        return render(request, self.template_name, context)


class PropertyDashBoard(LoginRequiredMixin, View):
    template_name = "properties/dashboard.html"

    def get(self, request):
        total_view_count = 0
        user = self.request.user
        user_agent = Agent.objects.get(business_user=user)
        property_count = Property.objects.filter(uploaded_by=user_agent).count()
        favourite_count = user.profile.favorite_properties.all().count()
        property_qs = Property.objects.filter(uploaded_by=user_agent)
        visitors_review_count = user.agent.agent_review.all().count()
        # Display The agent recent notifications...
        notifications = Notification.objects.filter(to_user=request.user, is_seen=False).order_by('-created_at')
        notification = Notification.objects.filter(to_user=request.user, is_seen=False)
        notification.update(is_seen=True)
        for instance in property_qs:
            total_view_count += instance.views_count
        context = {
            "property_count": property_count,
            "favourite_count": favourite_count,
            "total_view_count": total_view_count,
            "notifications": notifications,
            "visitors_review_count": visitors_review_count,
        }
        return render(request, self.template_name, context)


class PropertyDetailView(View):
    template_name = "properties/detail.html"
    
    def get(self, request, slug):
        property_obj = get_object_or_404(Property, slug=slug)
        similar_properties = Property.objects.filter(property_type=property_obj.property_type)\
            .filter(property_status=property_obj.property_status)\
            .filter(state=property_obj.state).exclude(slug=property_obj.slug)
        featured_properties = Property.objects.filter(featured=True).exclude(slug=property_obj.slug)
        property_obj.views_count = property_obj.views_count + 1
        property_obj.save()
        context = {
            "property": property_obj,
            "similar_properties": similar_properties,
            "featured_properties": featured_properties,
        }
        return render(request, self.template_name, context)


class PropertyCommentView(View):
    template_name = "properties/comment_list.html"

    def post(self, request, slug):
        get_property = get_object_or_404(Property, slug=slug)
        comment_val = self.request.POST.get("comment")
        print(comment_val)
        comment = Comment.objects.create(
            property=get_property,
            by=request.user,
            content=comment_val,
        )
        get_property.property_comment.add(comment)
        comments = get_property.property_comment.all()
        context = {
            "comments": comments,
        }
        return render(request, self.template_name, context)


class PropertyCreateView(LoginRequiredMixin, View):
    template_name = "properties/form.html"
    upload_price = 500
    featured_price = 500

    def get(self, request):
        form = PropertyForm()
        img_form = PropertyMediaForm()
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        states = get_states_only(file_path)
        wallet = self.request.user.wallet
        context = {
            'wallet': wallet,
            'upload_price': self.upload_price,
            'featured_price': self.featured_price,
            'form': form,
            'states': states,
            'img_form': img_form,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = PropertyForm(request.POST)
        img_form = PropertyMediaForm(request.FILES)
        state = self.request.POST.get("state")
        city = self.request.POST.get("city")
        my_files = self.request.FILES.getlist("file")
        wallet = self.request.user.wallet
        total_balance = 0
        if form.is_valid():
            f = form.save(commit=False)
            total_balance = self.upload_price
            # Update total_balance if featured button was clicked
            if f.featured:
                total_balance = self.upload_price + self.featured_price
            # Check for wallet balance and debit
            if wallet.balance >= total_balance:
                # Debit wallet but dont dave yet...
                wallet.balance = F('balance') - total_balance
                # Update form and save...
                f.uploaded_by = self.request.user.agent
                f.property_image = my_files[0]
                print(f"{my_files[0]} Saved successfully")
                del my_files[0]
                f.state = state
                f.city = city
                f.save()
                for mf in my_files:
                    img_doc = PropertyMedia.objects.create(
                        img_property=f,
                        property_image=mf,
                        uploaded_by=self.request.user
                    )
                    img_doc.save()
                # After saving the files then save wallet...
                wallet.save()
                # Update wallet transaction...
                wallet_transaction = WalletTransaction.objects.create(
                    wallet=wallet,
                    transaction_id=f.name[:6],
                    currency=wallet.currency,
                    amount=total_balance,
                    payment_status="successful",
                )
                wallet.wallet_transactions.add(wallet_transaction)
                messages.success(self.request, "Property added successfully")
                # return JsonResponse({'message': 'Property added successfully', 'status': 'success'}, status=200, safe=False)
                return redirect("properties:get_my_property_list")
            messages.error(self.request, "You currently have insufficient balance")
            return redirect("wallets:fund_wallet", wallet.uid)
        context = {
            'wallet': wallet,
            'featured_price': self.featured_price,
            'upload_price': total_balance,
            'form': form,
            'img_form': img_form,
        }
        messages.error(self.request, "You currently have insufficient balance")
        return render(request, self.template_name, context)


# def upload_file(request):
#     print(request.FILES.getlist('img_list'))
#     return JsonResponse("Ok", safe=False)


class PropertyUpdateView(LoginRequiredMixin, UpdateView):
    model = Property
    featured_price = 500
    template_name = "properties/edit.html"
    context_object_name = 'property'
    fields = (
        "name",
        "description",
        "property_type",
        "property_status",
        "payment_plan",
        "price",
        "plot_area",
        "no_bed_room",
        "no_bath_room",
        "property_image",
        "exterior_image1",
        "exterior_image2",
        "interior_image1",
        "interior_image2",
        "state",
        "city",
        "local_area",
        "street_address",
        "featured",
    )

    def get_page_title(self):
        obj = self.get_object()
        return f"Updated {obj.name}"

    def get_context_data(self, **kwargs):
        context = super(PropertyUpdateView, self).get_context_data()
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        context["states"] = get_states_only(file_path)
        wallet = self.request.user.wallet
        context["upload_price"] = 500
        context["featured_price"] = self.featured_price
        context["property"] = Property.objects.get(slug=self.kwargs.get("slug"))
        return context

    def form_valid(self, form):
        wallet = self.request.user.wallet
        agent = Agent.objects.get(business_user=self.request.user)
        state = self.request.POST.get("state")
        city = self.request.POST.get("city")
        print(state, city)
        # Debit wallet but dont dave yet...
        current_property = form.save(commit=False)
        # Update total_balance if featured button was clicked
        if current_property.featured and wallet.balance >= self.featured_price:
            wallet.balance = F('balance') - self.featured_price
            current_property.uploaded_by = agent
            current_property.uploaded_at = timezone.now()
            current_property.state = state
            current_property.city = city
            current_property.save()
            # After saving the files then save wallet...
            wallet.save()
            # Update wallet transaction...

apps/properties/templates/properties/comment_list.html
{% for pc in comments %}
    <div class="mbp_first media">
        <img class="rounded-circle mr-3" width="80px" height="80px" src="{{pc.by.profile.image_url}}" alt="{{pc.by}}">
        <div class="media-body">
            <h4 class="sub_title mt-0">{{pc.by.username}}</h4>
            <a class="sspd_postdate fz14">{{pc.created_on}}</a>
            <p class="mt10">{{pc.content}}</p>
        </div>
    </div>
{% empty %}
    <div class="mbp_first media">
        <h5>No reviews or comments yet</h5>
    </div>
{% endfor %}

apps/properties/templates/properties/dashboard.html
{% extends 'user_layout.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block content %}

    <div class="col-lg-12 mb10">
        <div class="breadcrumb_content style2">
            <h2 class="breadcrumb_title">Howdy, {{request.user.username|title}}!</h2>
            <p>We are glad to see you again!</p>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-3">
        <div class="ff_one">
            <div class="icon"><span class="flaticon-home"></span></div>
            <div class="detais">
                <div class="timer">{{property_count}}</div>
                <p>All Properties</p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-3">
        <div class="ff_one style2">
            <div class="icon"><span class="flaticon-view"></span></div>
            <div class="detais">
                <div class="timer">{{total_view_count}}</div>
                <p>Total Views</p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-3">
        <div class="ff_one style3">
            <div class="icon"><span class="flaticon-chat"></span></div>
            <div class="detais">
                <div class="timer">{{visitors_review_count}}</div>
                <p>Total Reviews</p>
            </div>
        </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-3">
        <div class="ff_one style4">
            <div class="icon"><span class="flaticon-heart"></span></div>
            <div class="detais">
                <div class="timer">{{favourite_count}}</div>
                <p>Total Favorites</p>
            </div>
        </div>
    </div>
    <div class="col-xl-7">
        <div class="application_statics">
            <h4>View Statistics</h4>
            <canvas id="myChart"></canvas>
        </div>
    </div>
    <div class="col-xl-5">
        <div class="recent_job_activity">
            <h4 class="title">Recent Activities</h4>
            {% for n in notifications %}
                <div class="grid">
                  <ul>
                      {% if n.notification_type == 1 %}
                          <li class="list-inline-item"><div class="icon"><i class="fa fa-credit-card fa-lg"></i></div></li>
                      {% elif n.notification_type == 2 %}
                          <li class="list-inline-item"><div class="icon"><span class="flaticon-home"></span></div></li>
                      {% elif n.notification_type == 3 %}
                          <li class="list-inline-item"><div class="icon"><i class="fa fa-envelope-o"></i></div></li>
                      {% elif n.notification_type == 4 %}
                          <li class="list-inline-item"><div class="icon"><i class="fa fa-pencil-square-o"></i></div></li>
                      {% elif n.notification_type == 5 %}
                          <li class="list-inline-item"><div class="icon"><i class="fa fa-star-o"></i></div></li>
                      {% elif n.notification_type == 6 %}
                        <li class="list-inline-item"><div class="icon"><span class="flaticon-chat"></span></div></li>
                      {% endif %}
                      <li class="list-inline-item"><p>{{n.message|safe}}</p></li>
                      <li class="list-inline-item">
                          <ul class="view_edit_delete_list">
                              <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="Delete">
                                  <a hx-delete="{% url 'notifications:delete' n.pk %}" hx-confirm="Do you wish to delete?" onClick="setTimeout(function(){ window.location.reload(); }, 3000);">
                                      <span class="flaticon-garbage"></span>
                                  </a>
                              </li>
                              {% if n.notification_type == 1 %}
                                  <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View">
                                      <a href="{% url 'wallets:wallet_transactions' %}">
                                          <span class="flaticon-view"></span>
                                      </a>
                                  </li>
                              {% elif n.notification_type == 2 %}
                                  <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View">
                                      <a href="{% url 'properties:detail' n.property.slug %}">
                                          <span class="flaticon-view"></span>
                                      </a>
                                  </li>
                              {% elif n.notification_type == 3 %}
                                  <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View">
                                      <a href="{% url 'inboxes:direct_msg' n.inbox_message.msg_sender.username %}">
                                          <span class="flaticon-view"></span>
                                      </a>
                                  </li>
                              {% elif n.notification_type == 4 %}
                                  <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View">
                                      <a href="{% url 'enquiries:my_enquiry_list' %}">
                                          <span class="flaticon-view"></span>
                                      </a>
                                  </li>
                              {% elif n.notification_type == 5 %}
                                  <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View">
                                      <a href="{% url 'agents:detail' n.review.slug %}">
                                          <span class="flaticon-view"></span>
                                      </a>
                                  </li>
                              {% elif n.notification_type == 6 %}
                                  <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="View">
                                      <a href="{% url 'properties:detail' n.property.slug %}">
                                          <span class="flaticon-view"></span>
                                      </a>
                                  </li>
                              {% endif %}
                          </ul>
                      </li>
                  </ul>
                </div>
            {% endfor %}
        </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'line',
    data: {
      labels: [{% for p in properties %} '{{p.name}}', {% endfor %}],
      datasets: [{
        label: '# of Properties',
        data: [{%for p in properties %} '{{p.uploaded_at|time}}', {%endfor%}],
        borderWidth: 1
      }]
    },
    options: {
      scales: {
        y: {
          beginAtZero: true
        }
<!--        x: [{-->
<!--            type: 'time'-->
<!--        }]-->
      }
    }
  });
</script>

{% endblock %}

apps/properties/templates/properties/my_property_list.html
{% extends 'user_layout.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block content %}

    <div class="col-lg-4 col-xl-4 mb10">
        <div class="breadcrumb_content style2 mb30-991">
            <h2 class="breadcrumb_title">My Properties</h2>
            <p>We are glad to see you again!</p>
        </div>
    </div>
<!--    <div class="col-lg-8 col-xl-8">-->
<!--        <div class="candidate_revew_select style2 text-right mb30-991">-->
<!--            <ul class="mb0">-->
<!--                <li class="list-inline-item">-->
<!--                    <div class="candidate_revew_search_box course fn-520">-->
<!--                        <form class="form-inline my-2">-->
<!--                            <input class="form-control mr-sm-2" type="search" placeholder="Search Courses" aria-label="Search">-->
<!--                            <button class="btn my-2 my-sm-0" type="submit"><span class="flaticon-magnifying-glass"></span></button>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                </li>-->
<!--                <li class="list-inline-item">-->
<!--                    <select class="selectpicker show-tick">-->
<!--                    <option>Featured First</option>-->
<!--                    <option>Recent</option>-->
<!--                    <option>Old Review</option>-->
<!--                </select>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
    <div class="col-lg-12">
        <div class="my_dashboard_review mb40">
            <div class="property_table">
                <div class="table-responsive mt0">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">Listing Title</th>
                                <th scope="col">Date published</th>
                                <th scope="col">Status</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for mp in my_properties %}
                                <tr>
                                    <th scope="row">
                                        <div class="feat_property list favorite_page style2">
                                            <div class="thumb">
                                                <img class="img-whp" src="{{mp.check_image_url}}" alt="{{mp.name}}">
                                                <div class="thmb_cntnt">
                                                    <ul class="tag mb0">
                                                        <li class="list-inline-item dn"></li>
                                                        <li class="list-inline-item">{{mp.property_status}}</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="details">
                                                <div class="tc_content">
                                                    <h4>{{mp.name}}</h4>
                                                    <p><span class="flaticon-placeholder"></span> {{mp.property_address}}</p>
                                                    <a class="fp_price text-thm">N{{mp.price|intword}}{% if mp.payment_plan %}<small>/{{mp.payment_plan}}</small>{% endif %}</a>
                                                </div>
                                            </div>
                                        </div>
                                    </th>
    <!--                                <td>{{mp.uploaded_at|date:"SHORT_DATE_FORMAT"}}</td>-->
                                    <td>{{mp.uploaded_at|date:"d M Y"}}</td>
                                    <td><span class="status_tag badge">{% if mp.featured %} Featured {% else %} Not-Featured {% endif %}</span></td>
    <!--                                <td>2,345</td>-->
                                    <td>
                                        <ul class="view_edit_delete_list mb0">
                                            <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="Edit"><a href="{% url 'properties:update' mp.slug %}"><span class="flaticon-edit"></span></a></li>
                                            <li class="list-inline-item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                <a hx-delete="{% url 'properties:delete' mp.slug %}" hx-confirm="Do you wish to delete?" onClick="setTimeout(function(){ window.location.reload(); }, 3000);">
                                                    <span class="flaticon-garbage"></span>
                                                </a>
                                            </li>
                                        </ul>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!-- Pagination -->
                <div class="mbp_pagination">
                    <ul class="page_navigation">
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true"> <span class="flaticon-left-arrow"></span> Prev</a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">...</a></li>
                        <li class="page-item"><a class="page-link" href="#">29</a></li>
                        <li class="page-item">
                            <a class="page-link" href="#"><span class="flaticon-right-arrow"></span></a>
                        </li>
                    </ul>
                </div>
                <!-- // Pagination // -->
            </div>
        </div>
    </div>

{% endblock %}