apps/accounts/urls.py
from django.urls import path
from apps.accounts import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.RegistrationView.as_view(), name='signup'),
    path('set-new-password/<uidb64>/<token>/', views.CompletePasswordResetView.as_view(), name='reset-user-password'),
    path('reset/', views.PasswordResetView.as_view(), name='reset-password'),
    path('activate/<uidb64>/<token>/', views.VerificationView.as_view(), name='activate'),
]

htmx_urlpatterns = [
    path('check_username/', views.check_username, name="check_username"),
    path('check_email/', views.check_email, name="check_email"),
    path('check_phone/', views.check_phone, name='check_phone'),
    path('check_password/', views.check_password, name="check_password"),
]

urlpatterns += htmx_urlpatterns

apps/agents/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views


urlpatterns = [
    # path('upload_file/', csrf_exempt(views.upload_file), name="upload_file"),
    path('my_reviews/', views.GetMyReviews.as_view(), name="my_reviews"),
    # path('my_agency_reviews/', views.GetMyAgencyReviews.as_view(), name="my_agency_reviews"),
    # path('my_property_reviews/', views.GetMyPropertyReviews.as_view(), name="my_property_reviews"),
    path('filter_agents/', csrf_exempt(views.filter_agents), name="filter_agents"),
    path('ratings/<slug:slug>/', csrf_exempt(views.AgentReviewView.as_view()), name='agent_ratings'),
    path('create/', csrf_exempt(views.AgentCreateView.as_view()), name='create'),
    path('get_cities/', csrf_exempt(views.GetStateCities.as_view()), name="get_cities"),
    path('<slug:slug>/', views.AgentDetailView.as_view(), name='detail'),
    path('', views.AgentListView.as_view(), name='list'),
]

apps/inboxes/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from apps.inboxes import views

urlpatterns = [
    path('', views.InboxMessageView.as_view(), name='inbox_msg'),
    path('<str:username>/', views.DirectMessage.as_view(), name='direct_msg'),
    path('send_direct_msg/', csrf_exempt(views.SendDirectMessage.as_view()), name='send_direct_msg'),
]

apps/wallets/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from apps.wallets.views import FundWalletView, WalletTransactionListView, confirm_fund_view

urlpatterns = [
    # path('validate_bvn/', csrf_exempt(ValidateBVN.as_view()), name='validate_bvn'),
    # path('<slug:id>/fund_success/', csrf_exempt(ConfirmFundView.as_view()), name='fund_success'),
    path('wallet_transactions/', WalletTransactionListView.as_view(), name='wallet_transactions'),
    path('<slug:uid>/', FundWalletView.as_view(), name='fund_wallet'),
    path('<slug:uid>/fund_success/', confirm_fund_view, name='fund_success'),
]

propertyDealsIn9ja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from propertyDealsIn9ja.settings import DEBUG
from propertyDealsIn9ja.views import HomeView, filter_property

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', csrf_exempt(HomeView.as_view()), name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/', include(('apps.accounts.urls', 'apps.accounts'), namespace='accounts')),
    path('api/accounts/', include(('apps.accounts.api.urls', 'apps.accounts'), namespace='api_accounts')),
    path('social-auth', include('social_django.urls', namespace='social')),
    path('profiles/', include(('apps.profiles.urls', 'apps.profiles'), namespace='profiles')),
    path('api/profiles/', include(('apps.profiles.api.urls', 'apps.profiles'), namespace='profiles_api')),
    path('contacts/', include(('apps.contacts.urls', 'apps.contacts'), namespace="contacts")),
    path('agents/', include(('apps.agents.urls', 'apps.agents'), namespace="agents")),
    path('properties/', include(('apps.properties.urls', 'apps.properties'), namespace="properties")),
    path('enquiries/', include(('apps.enquiries.urls', 'apps.enquiries'), namespace="enquiries")),
    path('wallets/', include(('apps.wallets.urls', 'apps.wallets'), namespace="wallets")),
    path('chats/', include(('apps.chats.urls', 'apps.chats'), namespace='chats')),
    path('inbox/', include(('apps.inboxes.urls', 'apps.inboxes'), namespace='inboxes')),
    path('notifications/', include(('apps.notifications.urls', 'apps.notifications'), namespace='notifications')),
    path('filter_property/', csrf_exempt(filter_property), name='filter_property'),

]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='404.html'))]

admin.site.site_header = "PropertyDealsIn9ja Admin"
admin.site.site_title = "PropertyDealsIn9ja Admin Portal"
admin.site.site_title = "Welcome to the PropertyDealsIn9ja administration"

templates/includes/filter_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}
    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-group has-danger" %}
        {% for error in field.errors %}
          <div class="form-control form-control-danger">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control has-success" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

templates/includes/search.html
{% load static %}
{% load widget_tweaks %}

<div class="container home_iconbox_container">
        <div class="row posr">
            <div class="col-lg-12">
                <div class="home_content home4">
                    <div class="home-text text-center">
                        <h2 class="fz55">Find Your Dream Home</h2>
                        <p class="fz18 color-white">From as low as N5,000 per month with limited time offer discounts.</p>
                    </div>
                </div>

                <div class="home_adv_srch_opt home7">
                    <div class="home1-advnc-search home7">
                        <form method="GET" action="{% url 'filter_property' %}">
                            {% csrf_token %}
                            <ul class="h1ads_1st_list mb0 text-center">
                                <li class="list-inline-item">
                                    <div class="search_option_two">
                                        <div class="candidate_revew_select">
                                            <select class="selectpicker w100 show-tick" name="property_type_exact_query">
                                                <option>All Cities</option>
                                                <option>Apartment</option>
                                                <option>Bungalow</option>
                                                <option>Condo</option>
                                                <option>House</option>
                                                <option>Land</option>
                                                <option>Single Family</option>
                                            </select>
                                        </div>
                                    </div>
                                </li>
                                <li class="list-inline-item">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="property_search_contain_query" id="exampleInputName1" placeholder="Search property or by agent">
                                    </div>
                                </li>
                                <li class="list-inline-item">
                                    <div class="search_option_button">
                                        <button type="submit" class="btn btn-thm">Search</button>
                                    </div>
                                </li>
                            </ul>
                        </form>
                    </div>
                </div>
            </div>
        </div>
<!--    <div class="row">-->
<!--        <div class="col-lg-12">-->
<!--            <h4 class="text-center color-white fw600 mb25 mb0-520">What are you looking for?</h4>-->
<!--            <ul class="home4_iconbox mb0">-->
<!--                <li class="list-inline-item">-->
<!--                    <div class="icon"><span class="flaticon-house"></span>-->
<!--                        <p>Modern Villa</p></div>-->
<!--                </li>-->
<!--                <li class="list-inline-item">-->
<!--                    <div class="icon"><span class="flaticon-house-1"></span>-->
<!--                        <p>Family House</p></div>-->
<!--                </li>-->
<!--                <li class="list-inline-item">-->
<!--                    <div class="icon"><span class="flaticon-house-2"></span>-->
<!--                        <p>Town House</p></div>-->
<!--                </li>-->
<!--                <li class="list-inline-item">-->
<!--                    <div class="icon"><span class="flaticon-building"></span>-->
<!--                        <p>Apartment</p></div>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
</div>

templates/includes/support_email.html
{% autoescape off %}
    <h3>Message from {{ name }}</h3>
    <p>Subject : {{ subject }}</p>
    <p>{{ message }}</p>
{% endautoescape %}

templates/includes/user_mobile_navbar.html
{% load static %}

<div class="dashboard_navigationbar dn db-992">
    <div class="dropdown">
        <button onclick="myFunction()" class="dropbtn"><i class="fa fa-bars pr10"></i> Dashboard Navigation</button>
        <ul id="myDropdown" class="dropdown-content">
            {% if request.user.is_staff %}
                <li><a href="/admin/"><span class="flaticon-layers"></span> Admin Dashboard</a></li>
            {% endif %}
            {% if request.user.is_agent %}
                <li><a href="{% url 'properties:property_dashboard' %}"><span class="flaticon-layers"></span> Dashboard</a></li>
                <li><a href="{% url 'properties:get_my_property_list' %}"><span class="flaticon-home"></span> My Properties</a></li>
                <li><a href="{% url 'properties:create' %}"><span class="flaticon-home"></span> Add Properties</a></li>
                <li><a href="{% url 'agents:my_reviews' %}"><span class="flaticon-chat"></span> My Reviews</a></li>
                <li><a href="{% url 'wallets:fund_wallet' request.user.wallet.uid %}"><i class="fa fa-credit-card fa-lg"></i> My Wallet</a></li>
                <li><a href="{% url 'enquiries:agent_enquiry_list' %}"><i class="fa fa-commenting-o fa-lg"></i> My Enquiries</a></li>
            {% else %}
                <li><a href="{% url 'enquiries:my_enquiries' %}"><i class="fa fa-commenting-o fa-lg"></i> My Enquiries</a></li>
            {% endif %}
            <li><a href="{% url 'inboxes:inbox_msg' %}"><span class="flaticon-envelope"></span> Message</a></li>
            <li><a href="{% url 'properties:get_favourites' %}"><span class="flaticon-heart"></span> My Favorites</a></li>
            <li>
                <a href="{% url 'profiles:profile_detail' request.user.profile.slug %}">
                    <span class="flaticon-user"></span> My Profile
                </a>
            </li>
            {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'profiles:profile_update' request.user.profile.slug %}">
                        <i class="fa fa-cogs"></i> Update Profile
                    </a>
                </li>
            {% endif %}
            <li><a href="{% url 'accounts:logout' %}"><span class="flaticon-logout"></span> Logout</a></li>
        </ul>
    </div>
</div>

templates/includes/user_mobile_sidebar.html
{% load static %}

<div class="dashboard_sidebar_menu dn-992">
    <ul class="sidebar-menu">
        <li class="header"><img width="120px" height="60px" src="https://res.cloudinary.com/geetechlab-com/image/upload/c_scale,h_500/v1672598092/propertyDealzin9ja/pd9ja_nav_logo-removebg-preview_qqpkjb.png" alt="header-logo2.png"></li>
        <li class="title"><span>Main</span></li>
        {% if request.user.is_agent %}
            <li class="treeview">
                <a href="{% url 'properties:property_dashboard' %}">
                    <i class="flaticon-layers"></i>
                    <span> Dashboard</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#"><i class="flaticon-home"></i>
                    <span>Properties</span>
                    <i class="fa fa-angle-down pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url 'properties:get_my_property_list' %}"><i class="fa fa-circle"></i> My Properties</a></li>
                    <li><a href="{% url 'properties:create' %}"><i class="fa fa-circle"></i> Add Properties</a></li>
                </ul>
            </li>
            <li><a href="{% url 'wallets:fund_wallet' request.user.wallet.uid %}"><i class="fa fa-credit-card"></i><span>My Wallet</span></a></li>
            <li class="treeview">
                <a href="page-my-review.html">
                    <i class="flaticon-chat"></i><span> Reviews</span>
                    <i class="fa fa-angle-down pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="{% url 'agents:my_reviews' %}"><i class="fa fa-circle"></i> My Reviews</a></li>
                </ul>
            </li>
            <li><a href="{% url 'enquiries:agent_enquiry_list' %}"><i class="fa fa-commenting-o fa-lg"></i> My Enquiries</span></a></li>
        {% endif %}
        <li class="treeview"><a href="{% url 'inboxes:inbox_msg' %}"><i class="flaticon-envelope"></i><span> Message</span></a></li>
        <li class="title"><span>Manage Listings</span></li>
        {% if request.user.is_authenticated and not request.user.is_agent %}
            <li><a href="{% url 'enquiries:my_enquiries' %}"><i class="fa fa-commenting-o fa-lg"></i> My Enquiries</span></a></li>
        {% endif %}
        <li><a href="{% url 'properties:get_favourites' %}"><i class="flaticon-heart"></i><span> My Favorites</span></a></li>
        <li class="title"><span>Manage Account</span></li>
        <li><a href="{% url 'profiles:profile_detail' request.user.profile.slug %}"><i class="flaticon-user"></i> <span>My Profile</span></a></li>
        <li><a href="{% url 'profiles:profile_update' request.user.profile.slug %}"><i class="fa fa-cogs"></i> <span>Update Profile</span></a></li>
        <li><a href="{% url 'accounts:logout' %}"><i class="flaticon-logout"></i> <span>Logout</span></a></li>
    </ul>
</div>

templates/includes/user_navbar.html
{% load static %}

<!-- Main Header Nav -->
<header class="header-nav menu_style_home_one style2 menu-fixed main-menu">
    <div class="container-fluid p0">
        <!-- Ace Responsive Menu -->
        <nav>
            <!-- Menu Toggle btn-->
            <div class="menu-toggle">
                <img class="nav_logo_img img-fluid" src="https://res.cloudinary.com/geetechlab-com/image/upload/v1672595643/propertyDealzin9ja/header-logo2_pficy7.png" alt="pdin9ja">
                <button type="button" id="menu-btn">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <a href="{% url 'home' %}" class="navbar_brand float-left dn-smd">
                <img class="logo1 img-fluid" src="{% static 'images/header-logo2.png' %}" alt="pdin9ja">
                <img class="logo2 img-fluid" src="{% static 'images/header-logo2.png' %}" alt="pdin9ja">
                <span>pd9ja</span>
            </a>
            <!-- Responsive Menu Structure-->
            <!--Note: declare the Menu style in the data-menu-style="horizontal" (options: horizontal, vertical, accordion) -->
            <ul id="respMenu" class="ace-responsive-menu text-right" data-menu-style="horizontal">
                <li><a href="{% url 'home' %}"><span class="title">Home</span></a></li>
                <li class="last"><a href="{% url 'properties:list' %}"><span class="title">Properties</span></a></li>
                {% if request.user.is_agent %}
                    <li class="last"><a href="{% url 'enquiries:list' %}"><span class="title">Enquiries</span></a></li>
                {% endif %}
                <li class="last"><a href="{% url 'agents:list' %}"><span class="title">Agents</span></a></li>
                <li class="last"><a href="{% url 'contacts:contact' %}"><span class="title">Contact</span></a></li>
                <li class="user_setting">
                    <div class="dropdown">
                        <a class="btn dropdown-toggle" href="#" data-toggle="dropdown">
                            <img class="rounded-circle" width="30px" height="30px" src="{{request.user.profile.image_url}}" alt="{{user.username}}">
                            <span class="dn-1199">{{request.user.username}}</span></a>
                        <div class="dropdown-menu">
                            <div class="user_set_header">
                                <img class="float-left" width="30px" height="30px" src="{{request.user.profile.image_url}}" alt="{{user.username}}">
                                <p>{{request.user.full_name}} <br><span class="address">{{request.user.email}}</span></p>
                            </div>
                            <hr>
                            <div class="user_setting_content">
                                <a class="dropdown-item" href="{% url 'profiles:profile_detail' request.user.profile.slug %}">My Profile</a>
                                <a class="dropdown-item" href="{% url 'profiles:profile_update' request.user.profile.slug %}">Update Profile</a>
                                {% if request.user.is_superuser %}
                                    <a class="dropdown-item" href="/admin/">Admin Dashboard</a>
                                {% endif %}
                                {% if request.user.is_agent %}
                                    <a class="dropdown-item" href="#">Fund Wallet</a>
                                {% endif %}
                                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log out</a>
                            </div>
                        </div>
                    </div>
                </li>
                {% if notifications.count %}
                    <li class="last">
                        <a data-toggle="modal" data-target=".notification_modal">
                            <span class="badge badge-pill badge-danger">
                                <i class="fa fa-bell-o fa-2x"></i>
                                <span class="badge badge-light">{{notifications.count}}</span>
                            </span>
                        </a>
                    </li>
                {% endif %}
                {% if request.user.is_agent %}
                    <li class="list-inline-item add_listing">
                        <a href="{% url 'properties:create' %}">
                            <span class="flaticon-plus"></span>
                            <span class="dn-lg"> Add Property</span>
                        </a>
                    </li>
                {% else %}
                    <li class="list-inline-item add_listing">
                        <a href="{% url 'enquiries:create' %}">
                            <span class="flaticon-plus"></span>
                            <span class="dn-lg"> Enquire</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

templates/includes/user_side_bar.html
{% load static %}

<!-- Main Header Nav For Mobile -->
<div id="page" class="stylehome1 h0">
    
    {% if request.user.is_authenticated %}
        <div class="mobile-menu">
            <div class="header stylehome1">
                <div class="main_logo_home2 text-center">
                    <img class="nav_logo_img img-fluid mt20" width="40px" height="40px" src="{{request.user.profile.image_url}}" alt="header-logo2.png">
                    <span class="mt20">{{request.user.username}}</span>
                </div>
                <ul class="menu_bar_home2">
                    <li class="list-inline-item list_s"><a href="{% url 'profiles:profile_detail' request.user.profile.slug %}"><span class="flaticon-user"></span></a></li>
                    <li class="list-inline-item"><a href="#menu"><span></span></a></li>
                </ul>
            </div>
        </div><!-- /.mobile-menu -->
    {% else %}
        <div class="mobile-menu">
            <div class="header stylehome1">
                <div class="main_logo_home2 text-center">
                    <img class="nav_logo_img img-fluid mt20" src="{% static 'images/header-logo2.png' %}" alt="header-logo2.png">
                    <span class="mt20">propertydealsin9ja</span>
                </div>
                <ul class="menu_bar_home2">
                    <li class="list-inline-item list_s"><a href="{% url 'accounts:signup' %}"><span class="flaticon-user"></span></a></li>
                    <li class="list-inline-item"><a href="#menu"><span></span></a></li>
                </ul>
            </div>
        </div><!-- /.mobile-menu -->
    {% endif %}
    <nav id="menu" class="stylehome1">
        <ul>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'properties:list' %}">Properties</a></li>
            {% if request.user.is_agent %}
                <li><a href="{% url 'enquiries:list' %}">Enquiries</a></li>
            {% endif %}
            <li><a href="{% url 'agents:list' %}">Agents</a></li>
            <li><a href="{% url 'contacts:contact' %}">Contact</a></li>
            {% if notifications.count %}
                <li>
                    <a data-toggle="modal" data-target=".notification_modal">
                        <span class="badge badge-pill badge-danger">
                            <i class="fa fa-bell-o fa-2x"></i>
                            <span class="badge badge-light">{{notifications.count}}</span>
                        </span>
                    </a>
                </li>
            {% endif %}
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}"><span class="flaticon-edit"></span> Log out</a></li>
                {% if request.user.is_agent %}
                    <li class="cl_btn">
                        <a class="btn btn-block btn-lg btn-thm circle" href="{% url 'properties:create' %}">
                            <span class="flaticon-plus"></span> Add Property
                        </a>
                    </li>
                {% else %}
                    <li class="cl_btn">
                        <a class="btn btn-block btn-thm circle" href="{% url 'enquiries:create' %}">
                            <span class="flaticon-plus"></span> Enquire
                        </a>
                    </li>
                {% endif %}
            {% else %}
                <li><a href="{% url 'accounts:login' %}"><span class="flaticon-user"></span> Login</a></li>
                <li><a href="{% url 'accounts:signup' %}"><span class="flaticon-edit"></span> Register</a></li>
            {% endif %}
        </ul>
    </nav>
</div>