apps/profiles/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('me/', views.ProfileAPIView.as_view(), name='get_profile'),
    path('update/<str:username>/', views.ProfileUpdateAPIView.as_view(), name='update_profile'),
]

apps/profiles/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views


urlpatterns = [
    # path('select_currency/', csrf_exempt(views.select_currency), name='select_currency'),
    path('<slug:slug>/', csrf_exempt(views.ProfileView.as_view()), name='profile_detail'),
    path('update/<slug:slug>/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('get_cities/<slug:slug>/', csrf_exempt(views.GetStateCities.as_view()), name="get_cities"),
]

apps/wallets/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from apps.wallets.views import FundWalletView, WalletTransactionListView, confirm_fund_view

urlpatterns = [
    # path('validate_bvn/', csrf_exempt(ValidateBVN.as_view()), name='validate_bvn'),
    # path('<slug:id>/fund_success/', csrf_exempt(ConfirmFundView.as_view()), name='fund_success'),
    path('wallet_transactions/', WalletTransactionListView.as_view(), name='wallet_transactions'),
    path('<slug:uid>/', FundWalletView.as_view(), name='fund_wallet'),
    path('<slug:uid>/fund_success/', confirm_fund_view, name='fund_success'),
]

propertyDealsIn9ja/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from propertyDealsIn9ja.settings import DEBUG
from propertyDealsIn9ja.views import HomeView, filter_property

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', csrf_exempt(HomeView.as_view()), name='home'),
    path('api-auth/', include('rest_framework.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/', include(('apps.accounts.urls', 'apps.accounts'), namespace='accounts')),
    path('api/accounts/', include(('apps.accounts.api.urls', 'apps.accounts'), namespace='api_accounts')),
    path('social-auth', include('social_django.urls', namespace='social')),
    path('profiles/', include(('apps.profiles.urls', 'apps.profiles'), namespace='profiles')),
    path('api/profiles/', include(('apps.profiles.api.urls', 'apps.profiles'), namespace='profiles_api')),
    path('contacts/', include(('apps.contacts.urls', 'apps.contacts'), namespace="contacts")),
    path('agents/', include(('apps.agents.urls', 'apps.agents'), namespace="agents")),
    path('properties/', include(('apps.properties.urls', 'apps.properties'), namespace="properties")),
    path('enquiries/', include(('apps.enquiries.urls', 'apps.enquiries'), namespace="enquiries")),
    path('wallets/', include(('apps.wallets.urls', 'apps.wallets'), namespace="wallets")),
    path('chats/', include(('apps.chats.urls', 'apps.chats'), namespace='chats')),
    path('inbox/', include(('apps.inboxes.urls', 'apps.inboxes'), namespace='inboxes')),
    path('notifications/', include(('apps.notifications.urls', 'apps.notifications'), namespace='notifications')),
    path('filter_property/', csrf_exempt(filter_property), name='filter_property'),

]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='404.html'))]

admin.site.site_header = "PropertyDealsIn9ja Admin"
admin.site.site_title = "PropertyDealsIn9ja Admin Portal"
admin.site.site_title = "Welcome to the PropertyDealsIn9ja administration"

apps/profiles/models.py
from autoslug import AutoSlugField
# from cloudinary.models import CloudinaryField
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from apps.common.models import TimeStampedUUIDModel
from django.utils.translation import gettext_lazy as _
from apps.accounts.models import User


def upload_dir(instance, filename):
    return "{}/{}/{}".format("user_photos", instance.user.username, filename)


class Gender(models.TextChoices):
    MALE = "Male", _("Male")
    FEMALE = "Female", _("Female")
    OTHER = "Other", _("Other")


class Profile(TimeStampedUUIDModel):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from='user', unique=True, always_update=True)
    gender = models.CharField(verbose_name=_("Gender"), max_length=20, choices=Gender.choices, default=Gender.OTHER)
    bio = models.TextField(verbose_name=_("About me"), default="Say something about yourself")
    image = models.ImageField(upload_to=upload_dir, blank=True, null=True)
    conversations = models.ManyToManyField('accounts.User', related_name='conversations', blank=True)
    country = CountryField(verbose_name=_("Country"), default="NG", blank=True, null=True)
    state = models.CharField(verbose_name=_("State"), max_length=100, blank=True, null=True)
    city = models.CharField(verbose_name=_("City"), max_length=100, blank=True, null=True)
    address = models.CharField(verbose_name=_("Address"), max_length=100, default="", blank=True, null=True)
    favorite_properties = models.ManyToManyField("properties.Property", blank=True)
    birth_day = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s profile"

    def get_absolute_url(self):
        return reverse('profiles:profile_detail', kwargs={'slug': self.slug})
    
    def get_user_address(self):
        return f"{self.address} {self.city} {self.state} {self.country.name}"

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return 'https://res.cloudinary.com/geetechlab-com/image/upload/v1583147406/nwaben.com/user_azjdde_sd2oje.jpg'

apps/profiles/forms.py
from currencies.models import Currency
from django import forms
from apps.profiles.models import Profile


class ProfileForm(forms.ModelForm):
    currency = forms.ModelChoiceField(queryset=Currency.objects.all(), required=False, help_text="Your currency")

    class Meta:
        model = Profile
        fields = (
            "image",
            "gender",
            "birth_day",
            "bio",
            "city",
        )

apps/profiles/api/views.py
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.profiles.api.exceptions import ProfileNotFound, NotYourProfile
from apps.profiles.api.renderers import ProfileJSONRenderer
from apps.profiles.api.serializers import ProfileSerializer, UpdateProfileSerializer
from apps.profiles.models import Profile


class ProfileAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    renderer_classes = [ProfileJSONRenderer]

    def get(self, request):
        user = self.request.user
        profile = Profile.objects.get(user=user)
        serializer = ProfileSerializer(profile, context={"request": request})
        return Response(serializer.data, status=status.HTTP_200_OK)


class ProfileUpdateAPIView(APIView):
    permission_classes = [permissions.IsAuthenticated]
    renderer_classes = [ProfileJSONRenderer]
    serializer_class = UpdateProfileSerializer

    def patch(self, request, username):
        try:
            Profile.objects.get(user__username=username)
        except Profile.DoesNotExist:
            raise ProfileNotFound

        user_name = request.user.username
        if user_name != username:
            raise NotYourProfile

        data = request.data
        serializer = UpdateProfileSerializer(
            instance=request.user.profile,
            data=data,
            partial=True
        )
        serializer.is_valid()
        serializer.save()
        return Response(serializer.data, status=status.HTTP_200_OK)

apps/profiles/views.py
import json
from os import stat
import os.path

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import DetailView, UpdateView
from django.views.generic.base import View
from tinify import tinify

from apps.profiles.models import Profile
from apps.wallets.models import Wallet
from propertyDealsIn9ja.utils import get_states, get_states_only, get_cities_only


class ProfileView(LoginRequiredMixin, DetailView):
    model = Profile
    context_object_name = 'profile'
    template_name = "profiles/profile.html"

    def get_object(self, queryset=None):
        return Profile.objects.get(slug=self.request.user.profile.slug)

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data()
        context["user"] = self.request.user
        return context


class GetStateCities(View):
    template_name = "profiles/profile_update.html"
        
    def post(self, request, slug):
        profile = Profile.objects.get(slug=slug)
        state = request.POST['state']
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        print(f"state from frontend {state}")
        cities = get_cities_only(file_path, state)
        print(cities)
        
        data = {
            "cities": cities,
            "success": "request was successful cities populated..."
        }
        return JsonResponse(data=data, safe=False)


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    template_name = "profiles/profile_update.html"
    context_object_name = 'profile'
    fields = (
        "gender",
        "bio",
        "image",
        "country",
        "city",
        "state",
        "address",
        "birth_day",
    )

    def get_object(self, queryset=None):
        return Profile.objects.get(slug=self.kwargs.get("slug"))
    
    def form_valid(self, form, *args, **kwargs):
        profile_inst = form.save(commit=False)
        state = self.request.POST.get("state")
        city = self.request.POST.get("city")
        print(state, city)
        profile_inst.state = state
        profile_inst.city = city
        if profile_inst.image:
            print(profile_inst.image)
        #     source = tinify.from_file(profile_inst.image).to_file(profile_inst.image)
        #     profile_inst.image = source
        profile_inst.save()
        messages.success(self.request, "Profile updated successfully...")
        return super(ProfileUpdateView, self).form_valid(form)
    
    # def post(self, request, **kwargs):
    #     state = self.request.POST.get("state")
    #     city = self.request.POST.get("city")
    #     print(state, city)
    #     profile = Profile.objects.get(slug=self.kwargs.get("slug"))
    #     profile.state = state
    #     profile.city = city
    #     profile.save(update_fields=['state', 'city'])
    #     messages.success(request, "Profile updated successfully...")
    #     return redirect("profiles:profile_detail", self.request.user.profile.slug)
    
    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data()
        file_path = "propertyDealsIn9ja/states-and-cities.json"
        context['states'] = get_states_only(file_path)
        context["user"] = Profile.objects.get(user=self.request.user)
        return context

apps/profiles/templates/profiles/forms.html
{% load widget_tweaks %}

<form method="post" id="currency_change_form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="fileinput fileinput-new text-center mt-5 mb-5" data-provides="fileinput">
        <div class="fileinput-new thumbnail img-circle img-no-padding" style="width: 100px; height: 100px;">
            <img src="{{ profile.image_url }}" alt="...">
        </div>
        <div class="fileinput-preview fileinput-exists thumbnail img-circle img-no-padding"
             style="max-width: 150px; max-height: 150px;"></div>
        <div>
            <span class="btn btn-outline-default btn-file btn-round">
                <span class="fileinput-new">Add Photo</span>
                <span class="fileinput-exists">Change</span>
{#                <input type="file" name="...">#}
                {% render_field form.image|attr:"type:file" %}
            </span>
            <br>
            <a href="javascript:;" class="btn btn-link btn-danger fileinput-exists btn-round"
               data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
        </div>
    </div>

    <div class="form-group">
        <label class="text-justify">Gender</label>
        {% render_field form.gender class="form-control" placeholder=form.gender.help_text %}
    </div>
    <div class="form-group">
        <label class="text-justify">About me</label>
        {% render_field form.bio class="form-control" placeholder=form.bio.help_text %}
    </div>
    <div class="form-group">
        <label class="text-justify">Country</label>
        <input class="form-control" value="{{ profile.country.name }}" id="wallet_country" disabled>
    </div>
    <div class="form-group">
        <label class="text-justify">City</label>
        {% render_field form.city class="form-control" placeholder=form.city.help_text %}
    </div>
    <button class="btn btn-rotate btn-round" type="submit" id="submit_currency">
        <i class="fa fa-cog"></i>update profile
    </button>
</form>

apps/profiles/templates/profiles/me.html
{% extends 'layout.html' %}
{% load humanize %}
{% load currency %}

{% block title %}{{ profile.user.username }}{% endblock %}

{% block content %}
<div class="profile-page sidebar-collapse">
  <div class="page-header page-header-small" style="background-image: url('https://res.cloudinary.com/geetechlab-com/image/upload/v1659898814/nwaben.com/daddy_heaven_5_cmciv1.jpg');">
    <div class="filter"></div>
  </div>
  <div class="wrapper">
    <div class="profile-content section">
      <div class="container">
        <div class="row">
          <div class="profile-picture">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new img-no-padding">
                <img src="{{ profile.image_url }}" alt="{{ profile.user.username }}">
              </div>
              <div class="name">
                <h4 class="title text-center">{{ profile.user.get_full_name }}
                  <br />
                    {% if profile.gender %}
                        <small>Gender : {{ profile.gender }}</small>
                    {% else %}
                        <small>No Gender yet</small>
                    {% endif %}
                </h4>
                <h4 class="title-brand text-center mb-5">
                    My Wallet Balance:
                    <b>
                        {{ request.user.wallet.currency }} {{ request.user.wallet.balance|intcomma }}
                    </b>
                </h4>
                  <a class="btn btn-round btn-sm btn-primary" href="{% url 'memorials:create' %}">
                      <i class="fa fa-plus"></i> Upload a Memory
                  </a>
                  <a class="btn btn-round btn-sm btn-primary" href="{% url 'wallets:fund_wallet' request.user.wallet.uid %}">
                      <i class="fa fa-money"></i> Fund my wallet
                  </a>
              </div>
            </div>
          </div>
        </div>
        <br/>
        <div class="nav-tabs-navigation">
          <div class="nav-tabs-wrapper">
            <ul class="nav nav-tabs" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#details" role="tab">
                    Details
                </a>
              </li>
            {% if profile.user == request.user %}
              <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#update_details" role="tab">
                    Update my details
                </a>
              </li>
            {% endif %}
            </ul>
          </div>
        </div>
        <!-- Tab panes -->
        <div class="tab-content">
          <div class="tab-pane active" id="details" role="tabpanel">
            <div class="row">
                <div class="info">
                    <div class="description text-justify">
                        {% if profile.bio %}
                            <p>{{ profile.bio }}</p>
                        {% else %}
                            <h4 class="info-title">Tell us about your self.</h4>
                            <p>Example: About your previous achievements, your family, what you are currently doing and your current location</p>
                        {% endif %}
                        <br>
                        <hr width="80%">
                        <h5 class="title">My contacts</h5>
                        <i class="fa fa-mobile-phone text-primary fa-2x mr-3 mb-3"></i><strong>{{ profile.user.phone }}</strong>
                        <br>
                        <i class="fa fa-at text-primary fa-2x mr-3"></i> <strong>{{ profile.user.email }}</strong>
                        <hr width="80%">
                        <h5 class="title">My Address</h5>
                        <i class="fa fa-globe text-primary fa-2x mr-3 mb-3"></i> <strong>{{ profile.country.name }}</strong>
                        <br>
                        <i class="fa fa-map-marker text-primary fa-2x mr-3"></i> <strong>{{ profile.city }}</strong>
                    </div>
                </div>
            </div>
          </div>

        {% if profile.user == request.user %}
          <div class="tab-pane text-center" id="update_details" role="tabpanel">
            <div class="col-md-6 ml-auto mr-auto text-center">
                {% include "profiles/forms.html" %}
            </div>
          </div>
        {% endif %}

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/profiles/templates/profiles/profile.html
{% extends 'user_layout.html' %}
{% load static %}
{% load humanize %}
{% load widget_tweaks %}

{% block content %}
	<div class="col-lg-12 mb10">
		<div class="breadcrumb_content style2">
			<h2 class="breadcrumb_title">My Profile</h2>
			<p>We are glad to see you again <strong>{{ user.username }}</strong>!</p>
		</div>
	</div>
	<div class="col-lg-12">
		<div class="my_dashboard_review">
			<div class="row">
				<div class="col-xl-12 mt40">
					<div class="feat_property list style2 agent">
						<div class="thumb">
							<img class="img-whp" src="{{user.profile.image_url}}" height="250px" alt="{{user.username}}">
							<div class="thmb_cntnt">
							</div>
						</div>
						<div class="details">
							<div class="tc_content">
								<h4>{{user.full_name}}</h4>
									<p class="text-thm">Update Profile</p>
								<ul class="prop_details mb0">
									<li><a><strong>Current Address: </strong>{{user.profile.get_user_address}}</a></li>
									<li><a><strong>Gender: </strong>{{user.profile.gender}}</a></li>
									<li><a><strong>Mobile: </strong>{{user.phone}}</a></li>
									<li><a><strong>Email: </strong>{{user.email}}</a></li>
									{% if user.is_agent %}
										<li><a><strong>Balance: </strong>{{user.wallet.currency}}{{user.wallet.balance|intcomma}}</a></li>
									{% endif %}
								</ul>
							</div>
							<div class="fp_footer"> 
								<ul class="fp_meta float-left mb0">
									<li class="list-inline-item">visit our social media for more: </li>
									<li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
									<li class="list-inline-item"><a href="#"><i class="fa fa-google"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				{% if user.is_agent %}
					<div class="col-xl-12 mt20">
						<div class="feat_property list agency">
							<div class="thumb">
								<img class="img-whp" src="{{user.agent.business_logo_url}}" alt="{{user.agent.business_name}}">
								<div class="thmb_cntnt">
									<ul class="tag mb0">
										<li class="list-inline-item dn"></li>
										<li class="list-inline-item"><a href="#">{{user.agent.properties.count}} Listings</a></li>
									</ul>
								</div>
							</div>
							<div class="details">
								<div class="tc_content">
									<h4>{{user.agent.business_name}}</h4>
									<p class="text-thm">Agent</p>
									<ul class="prop_details mb0">
										<li><a>Office: {{user.agent.get_business_address}}</a></li>
										<li><a>Mobile: {{user.agent.get_business_phone}}</a></li>
										<li><a>Email: {{user.agent.get_business_email}}</a></li>
										<li><a>Date Registered: {{user.agent.date_registered|naturalday}}</a></li>
										<li><a>Balance: {{user.wallet.currency}}{{user.wallet.balance|intcomma}}</a></li>
									</ul>
								</div>
								<div class="fp_footer">
									{% comment %} <ul class="fp_meta float-left mb0">
										<li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
										<li class="list-inline-item"><a href="#"><i class="fa fa-google"></i></a></li>
									</ul> {% endcomment %}
									{%if request.user.is_authenticated and request.user.is_agent%}
										<div class="fp_pdate float-right text-thm">View My Listings <i class="fa fa-angle-right"></i></div>
									{%endif%}
								</div>
							</div>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>

{% endblock %}

apps/profiles/templates/profiles/profile_update.html
{% extends 'user_layout.html' %}
{% load widget_tweaks %}

{% block content %}
	<div class="col-lg-12 mb10">
		<div class="breadcrumb_content style2">
			<h2 class="breadcrumb_title">Update Profile</h2>
			<p>We are glad to see you again!</p>
		</div>
	</div>
	<div class="col-lg-12">
		<div class="my_dashboard_review">
			<div class="row">
				<div class="col-xl-2">
					<h4>Profile Information</h4>
				</div>
				<div class="col-xl-10 mt30">
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="row">
							<div class="col-lg-12 mb10">
								<div class="wrap-custom-file">
									{% render_field form.image|attr:"type:file"|attr:"id:image" %}
									<label style="{background-image: url({{request.user.profile.image_url}})}"  for="image">
										<span><i class="flaticon-download"></i> Upload Photo </span>
									</label>
								</div>
								<p>*minimum 260px x 260px</p>
							</div>
							<div class="col-lg-6 col-xl-6">
								<div class="my_profile_setting_input form-group">
									<label for="formGroupExampleUsername">Username</label>
									<input type="text" class="form-control" id="formGroupExampleUsername" value="{{ request.user.username }}" readonly>
								</div>
							</div>
							<div class="col-lg-6 col-xl-6">
								<div class="my_profile_setting_input form-group">
									<label for="formGroupExampleEmail">Email</label>
									<input type="email" class="form-control" id="formGroupExampleEmail" value="{{ request.user.email }}" readonly>
								</div>
							</div>
							<div class="col-lg-6 col-xl-6">
								<div class="my_profile_setting_input form-group">
									<label for="formGroupExampleInput3">Fullname</label>
									<input type="text" class="form-control" id="formGroupExampleInput3" value="{{ request.user.full_name }}" readonly>
								</div>
							</div>
							<div class="col-lg-6 col-xl-6">
								<div class="ui_kit_select_box">
									<label>Gender</label>
									{% render_field form.gender class="selectpicker custom-select-lg mb-3" placeholder=form.gender.help_text %}
								</div>
							</div>
							<div class="col-lg-6 col-xl-6">
								<div class="my_profile_setting_input form-group">
									<label>Phone</label>
									<input type="text" class="form-control" value="{{ request.user.phone }}" readonly>
								</div>
							</div>
							<div class="col-lg-6 col-xl-6">
								<div class="my_profile_setting_input form-group">
									<label>Country</label>
									<input type="text" class="form-control" value="{{ request.user.profile.country.name }}" readonly>
								</div>
							</div>
							<div class="col-lg-6 col-xl-6">
<!--								<div class="my_profile_setting_input form-group">-->
<!--									<label>State</label>-->
<!--									{% render_field form.state class="form-control" placeholder=form.city.help_text %}-->
<!--								</div>-->
								<div class="ui_kit_select_box">
									<label>State</label>
									<select class="selectpicker custom-select-lg mb-3" id="selected_state" name="state" required>
										{% for s in states %}
											{% if s == request.user.profile.state %}
												<option value="{{request.user.profile.state}}" selected>{{request.user.profile.state}}</option>
											{% else %}
												<option value="{{s}}">{{s}}</option>
											{% endif %}
										{% endfor %}
									</select>
								</div>
							</div>

							<div class="col-lg-6 col-xl-6">
<!--								<div class="my_profile_setting_input form-group">-->
<!--									<label>City</label>-->
<!--									{% render_field form.city class="form-control" placeholder=form.city.help_text %}-->
<!--								</div>-->
								<div class="ui_kit_select_box">
									<label>City/LGA</label>
									<select class="form-control form-control-lg" id="selected_city" name="city" required>
										{% comment %} <option value="" disabled selected>Select city</option> {% endcomment %}
										{% if request.user.profile.city %}
											<option value="{{request.user.profile.city}}" disabled selected>{{request.user.profile.city}}</option>
										{% else %}
											<option value="" disabled selected>Select city</option>
										{% endif %}
									</select>
								</div>
							</div>
							<div class="col-lg-12 col-xl-12">
								<div class="my_profile_setting_input form-group">
									<label>Street Address</label>
									{% render_field form.address class="form-control" placeholder=form.city.help_text %}
								</div>
							</div>
							<div class="col-xl-12">
								<div class="my_profile_setting_textarea">
									<label>About me</label>
									{% render_field form.bio|attr:"rows: 4" class="form-control" placeholder=form.bio.help_text %}
								</div>
							</div>
							<div class="col-xl-12 text-right">
								<div class="my_profile_setting_input">
									<button class="btn btn2" type="submit">Update Profile</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$("#selected_state").on("change", function () {
				let stateVal = $("#selected_state").val();

				console.log(stateVal);
				$.ajax({
					url: "{% url 'profiles:get_cities' request.user.profile.slug %}",
					type: "post",
					data: {
						"state": stateVal,
						"csrfmiddlewaretoken": "{{csrf_token}}"
					},
					dataType: "json",
					before: function () {

					},
					success: function (res) {
						let cities = res.cities;
						console.log(res.success);
						$('#selected_city').empty();
						$.each(cities, function(index, item)
						{
							console.log(item);
							$("#selected_city").append("<option value='"+item +"'>"+item +"</option>");
						});

						console.log("worked till here... \n\n\n");
					}
				})
			});
		});
	</script>

{% endblock %}